-------------------Log----------------24/04/05-11:10:25
Traceback (most recent call last):
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jws.py", line 257, in _load
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\auth_middleware.py", line 34, in decorated
    payload = jwt.decode(token, current_app.config['SECRET_KEY'],algorithms=["HS256"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jwt.py", line 210, in decode
    decoded = self.decode_complete(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jwt.py", line 151, in decode_complete
    decoded = api_jws.decode_complete(
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jws.py", line 198, in decode_complete
    payload, signing_input, header, signature = self._load(jwt)
                                                ^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jws.py", line 260, in _load
    raise DecodeError("Not enough segments") from err
jwt.exceptions.DecodeError: Not enough segments
 ---- token_required
-------------------Log----------------24/04/05-11:10:30
Traceback (most recent call last):
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jws.py", line 257, in _load
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\auth_middleware.py", line 34, in decorated
    payload = jwt.decode(token, current_app.config['SECRET_KEY'],algorithms=["HS256"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jwt.py", line 210, in decode
    decoded = self.decode_complete(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jwt.py", line 151, in decode_complete
    decoded = api_jws.decode_complete(
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jws.py", line 198, in decode_complete
    payload, signing_input, header, signature = self._load(jwt)
                                                ^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jws.py", line 260, in _load
    raise DecodeError("Not enough segments") from err
jwt.exceptions.DecodeError: Not enough segments
 ---- token_required
-------------------Log----------------24/04/05-11:10:34
Traceback (most recent call last):
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jws.py", line 257, in _load
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\auth_middleware.py", line 34, in decorated
    payload = jwt.decode(token, current_app.config['SECRET_KEY'],algorithms=["HS256"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jwt.py", line 210, in decode
    decoded = self.decode_complete(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jwt.py", line 151, in decode_complete
    decoded = api_jws.decode_complete(
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jws.py", line 198, in decode_complete
    payload, signing_input, header, signature = self._load(jwt)
                                                ^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jws.py", line 260, in _load
    raise DecodeError("Not enough segments") from err
jwt.exceptions.DecodeError: Not enough segments
 ---- token_required
-------------------Log----------------24/04/05-11:10:43
Traceback (most recent call last):
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jws.py", line 257, in _load
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\auth_middleware.py", line 34, in decorated
    payload = jwt.decode(token, current_app.config['SECRET_KEY'],algorithms=["HS256"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jwt.py", line 210, in decode
    decoded = self.decode_complete(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jwt.py", line 151, in decode_complete
    decoded = api_jws.decode_complete(
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jws.py", line 198, in decode_complete
    payload, signing_input, header, signature = self._load(jwt)
                                                ^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jws.py", line 260, in _load
    raise DecodeError("Not enough segments") from err
jwt.exceptions.DecodeError: Not enough segments
 ---- token_required
-------------------Log----------------24/04/05-11:10:53
Traceback (most recent call last):
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jws.py", line 257, in _load
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\auth_middleware.py", line 34, in decorated
    payload = jwt.decode(token, current_app.config['SECRET_KEY'],algorithms=["HS256"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jwt.py", line 210, in decode
    decoded = self.decode_complete(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jwt.py", line 151, in decode_complete
    decoded = api_jws.decode_complete(
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jws.py", line 198, in decode_complete
    payload, signing_input, header, signature = self._load(jwt)
                                                ^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jws.py", line 260, in _load
    raise DecodeError("Not enough segments") from err
jwt.exceptions.DecodeError: Not enough segments
 ---- token_required
-------------------Log----------------24/04/05-11:11:19
Traceback (most recent call last):
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jws.py", line 257, in _load
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\auth_middleware.py", line 34, in decorated
    payload = jwt.decode(token, current_app.config['SECRET_KEY'],algorithms=["HS256"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jwt.py", line 210, in decode
    decoded = self.decode_complete(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jwt.py", line 151, in decode_complete
    decoded = api_jws.decode_complete(
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jws.py", line 198, in decode_complete
    payload, signing_input, header, signature = self._load(jwt)
                                                ^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jws.py", line 260, in _load
    raise DecodeError("Not enough segments") from err
jwt.exceptions.DecodeError: Not enough segments
 ---- token_required
-------------------Log----------------24/04/05-11:11:41
Traceback (most recent call last):
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jws.py", line 257, in _load
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\auth_middleware.py", line 34, in decorated
    payload = jwt.decode(token, current_app.config['SECRET_KEY'],algorithms=["HS256"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jwt.py", line 210, in decode
    decoded = self.decode_complete(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jwt.py", line 151, in decode_complete
    decoded = api_jws.decode_complete(
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jws.py", line 198, in decode_complete
    payload, signing_input, header, signature = self._load(jwt)
                                                ^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jws.py", line 260, in _load
    raise DecodeError("Not enough segments") from err
jwt.exceptions.DecodeError: Not enough segments
 ---- token_required
-------------------Log----------------24/04/05-11:11:54
Traceback (most recent call last):
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jws.py", line 257, in _load
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\auth_middleware.py", line 34, in decorated
    payload = jwt.decode(token, current_app.config['SECRET_KEY'],algorithms=["HS256"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jwt.py", line 210, in decode
    decoded = self.decode_complete(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jwt.py", line 151, in decode_complete
    decoded = api_jws.decode_complete(
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jws.py", line 198, in decode_complete
    payload, signing_input, header, signature = self._load(jwt)
                                                ^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jws.py", line 260, in _load
    raise DecodeError("Not enough segments") from err
jwt.exceptions.DecodeError: Not enough segments
 ---- token_required
-------------------Log----------------24/04/05-11:12:11
Traceback (most recent call last):
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jws.py", line 257, in _load
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\auth_middleware.py", line 34, in decorated
    payload = jwt.decode(token, current_app.config['SECRET_KEY'],algorithms=["HS256"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jwt.py", line 210, in decode
    decoded = self.decode_complete(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jwt.py", line 151, in decode_complete
    decoded = api_jws.decode_complete(
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jws.py", line 198, in decode_complete
    payload, signing_input, header, signature = self._load(jwt)
                                                ^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jws.py", line 260, in _load
    raise DecodeError("Not enough segments") from err
jwt.exceptions.DecodeError: Not enough segments
 ---- token_required
-------------------Log----------------24/04/05-11:12:38
Traceback (most recent call last):
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jws.py", line 257, in _load
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\auth_middleware.py", line 34, in decorated
    payload = jwt.decode(token, current_app.config['SECRET_KEY'],algorithms=["HS256"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jwt.py", line 210, in decode
    decoded = self.decode_complete(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jwt.py", line 151, in decode_complete
    decoded = api_jws.decode_complete(
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jws.py", line 198, in decode_complete
    payload, signing_input, header, signature = self._load(jwt)
                                                ^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jws.py", line 260, in _load
    raise DecodeError("Not enough segments") from err
jwt.exceptions.DecodeError: Not enough segments
 ---- token_required
-------------------Log----------------24/04/05-11:13:07
Traceback (most recent call last):
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jws.py", line 257, in _load
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\auth_middleware.py", line 34, in decorated
    payload = jwt.decode(token, current_app.config['SECRET_KEY'],algorithms=["HS256"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jwt.py", line 210, in decode
    decoded = self.decode_complete(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jwt.py", line 151, in decode_complete
    decoded = api_jws.decode_complete(
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jws.py", line 198, in decode_complete
    payload, signing_input, header, signature = self._load(jwt)
                                                ^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jws.py", line 260, in _load
    raise DecodeError("Not enough segments") from err
jwt.exceptions.DecodeError: Not enough segments
 ---- token_required
-------------------Log----------------24/04/05-11:14:56
Traceback (most recent call last):
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jws.py", line 257, in _load
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\auth_middleware.py", line 34, in decorated
    payload = jwt.decode(token, current_app.config['SECRET_KEY'],algorithms=["HS256"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jwt.py", line 210, in decode
    decoded = self.decode_complete(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jwt.py", line 151, in decode_complete
    decoded = api_jws.decode_complete(
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jws.py", line 198, in decode_complete
    payload, signing_input, header, signature = self._load(jwt)
                                                ^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jws.py", line 260, in _load
    raise DecodeError("Not enough segments") from err
jwt.exceptions.DecodeError: Not enough segments
 ---- token_required
-------------------Log----------------24/04/05-11:18:37
accessToken ---- abc
-------------------Log----------------24/04/05-11:18:37
154281130814958933425240769184967185190 ---- abc
-------------------Log----------------24/04/05-11:18:37
Traceback (most recent call last):
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jws.py", line 257, in _load
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\auth_middleware.py", line 35, in decorated
    payload = jwt.decode(token, current_app.config['SECRET_KEY'],algorithms=["HS256"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jwt.py", line 210, in decode
    decoded = self.decode_complete(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jwt.py", line 151, in decode_complete
    decoded = api_jws.decode_complete(
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jws.py", line 198, in decode_complete
    payload, signing_input, header, signature = self._load(jwt)
                                                ^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\jwt\api_jws.py", line 260, in _load
    raise DecodeError("Not enough segments") from err
jwt.exceptions.DecodeError: Not enough segments
 ---- token_required